# Generated by Django 4.2 on 2023-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgform',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
