# Generated by Django 4.2 on 2023-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgform', '0002_alter_imgform_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgform',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
